/**:
  ros__parameters:

    local_position:
      # This sets the frame_id of the /mavros/local_position/pose topic
      frame_id: "map" 

      # TF broadcasting parameters
      tf:
        # Set this to true to broadcast the transform
        send: true
        
        # Parent frame of the transform (what we are relative to)
        frame_id: "map" 
        
        # Child frame of the transform (the drone itself)
        child_frame_id: "base_link"
        
        # This sends the TF to the flight controller, usually not needed.
        send_fcu: false